- name: Clone projectFolder-spring-api project
  git:
    repo: "https://github.com/gov-ithub/projectFolder-spring-api.git"
    dest: "/tmp/projectFolder-spring-api"
    force: yes

- name: Build projectFolder-spring-api
  shell: "/usr/bin/mvn clean package"
  args:
    chdir: "/tmp/projectFolder-spring-api"