---
# tasks file for basic
- name: Remove packages
  apt: name="{{ item }}" state="absent"
  with_items:
    - apache2
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int >= 14
